name: SimpleCam
version: 1.1
main: com.maijsoft.simplecam.CameraPlugin
api-version: 1.21
description: A camera movement plugin for Minecraft
commands:
  cm:
    description: 카메라 시스템 명령어
    usage: /cm <subcommand> ...
    aliases: [camera]
    permission: camera.use
permissions:
  camera.use:
    description: 카메라 명령어 사용 권한
    default: op
