name: SimpleCam
version: 1.0
main: com.maijsoft.simplecam.Main
api-version: 1.21
description: A camera movement plugin for Minecraft
commands:
  cm:
    description: Camera plugin commands
    usage: /cm <subcommand>
    aliases: [camera]
